#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("RecyclerDemo.Resource", IsApplication=true)]

namespace RecyclerDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::RecyclerViewFastScroller.Resource.Attribute.backgroundColor = global::RecyclerDemo.Resource.Attribute.backgroundColor;
			global::RecyclerViewFastScroller.Resource.Attribute.barBackground = global::RecyclerDemo.Resource.Attribute.barBackground;
			global::RecyclerViewFastScroller.Resource.Attribute.barColor = global::RecyclerDemo.Resource.Attribute.barColor;
			global::RecyclerViewFastScroller.Resource.Attribute.fast_scroller_layout = global::RecyclerDemo.Resource.Attribute.fast_scroller_layout;
			global::RecyclerViewFastScroller.Resource.Attribute.handleBackground = global::RecyclerDemo.Resource.Attribute.handleBackground;
			global::RecyclerViewFastScroller.Resource.Attribute.handleColor = global::RecyclerDemo.Resource.Attribute.handleColor;
			global::RecyclerViewFastScroller.Resource.Attribute.layoutManager = global::RecyclerDemo.Resource.Attribute.layoutManager;
			global::RecyclerViewFastScroller.Resource.Attribute.reverseLayout = global::RecyclerDemo.Resource.Attribute.reverseLayout;
			global::RecyclerViewFastScroller.Resource.Attribute.section_indicator_layout = global::RecyclerDemo.Resource.Attribute.section_indicator_layout;
			global::RecyclerViewFastScroller.Resource.Attribute.spanCount = global::RecyclerDemo.Resource.Attribute.spanCount;
			global::RecyclerViewFastScroller.Resource.Attribute.stackFromEnd = global::RecyclerDemo.Resource.Attribute.stackFromEnd;
			global::RecyclerViewFastScroller.Resource.Attribute.textColor = global::RecyclerDemo.Resource.Attribute.textColor;
			global::RecyclerViewFastScroller.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::RecyclerDemo.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::RecyclerViewFastScroller.Resource.Dimension.list_item_height = global::RecyclerDemo.Resource.Dimension.list_item_height;
			global::RecyclerViewFastScroller.Resource.Dimension.margin_huge = global::RecyclerDemo.Resource.Dimension.margin_huge;
			global::RecyclerViewFastScroller.Resource.Dimension.margin_large = global::RecyclerDemo.Resource.Dimension.margin_large;
			global::RecyclerViewFastScroller.Resource.Dimension.margin_medium = global::RecyclerDemo.Resource.Dimension.margin_medium;
			global::RecyclerViewFastScroller.Resource.Dimension.margin_small = global::RecyclerDemo.Resource.Dimension.margin_small;
			global::RecyclerViewFastScroller.Resource.Dimension.margin_tiny = global::RecyclerDemo.Resource.Dimension.margin_tiny;
			global::RecyclerViewFastScroller.Resource.Drawable.fast_scroller_handle_rounded = global::RecyclerDemo.Resource.Drawable.fast_scroller_handle_rounded;
			global::RecyclerViewFastScroller.Resource.Drawable.section_indicator_background_default_rounded = global::RecyclerDemo.Resource.Drawable.section_indicator_background_default_rounded;
			global::RecyclerViewFastScroller.Resource.Id.item_touch_helper_previous_elevation = global::RecyclerDemo.Resource.Id.item_touch_helper_previous_elevation;
			global::RecyclerViewFastScroller.Resource.Id.scroll_bar = global::RecyclerDemo.Resource.Id.scroll_bar;
			global::RecyclerViewFastScroller.Resource.Id.scroll_handle = global::RecyclerDemo.Resource.Id.scroll_handle;
			global::RecyclerViewFastScroller.Resource.Id.section_indicator_text = global::RecyclerDemo.Resource.Id.section_indicator_text;
			global::RecyclerViewFastScroller.Resource.Id.section_title_popup = global::RecyclerDemo.Resource.Id.section_title_popup;
			global::RecyclerViewFastScroller.Resource.Layout.section_indicator_with_title = global::RecyclerDemo.Resource.Layout.section_indicator_with_title;
			global::RecyclerViewFastScroller.Resource.Layout.vertical_recycler_fast_scroller_layout = global::RecyclerDemo.Resource.Layout.vertical_recycler_fast_scroller_layout;
			global::RecyclerViewFastScroller.Resource.String.app_name = global::RecyclerDemo.Resource.String.app_name;
			global::RecyclerViewFastScroller.Resource.String.library_name = global::RecyclerDemo.Resource.String.library_name;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller_barBackground = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller_barBackground;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller_barColor = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller_barColor;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller_fast_scroller_layout = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller_fast_scroller_layout;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller_handleBackground = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller_handleBackground;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsRecyclerViewFastScroller_handleColor = global::RecyclerDemo.Resource.Styleable.AbsRecyclerViewFastScroller_handleColor;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsSectionIndicator = global::RecyclerDemo.Resource.Styleable.AbsSectionIndicator;
			global::RecyclerViewFastScroller.Resource.Styleable.AbsSectionIndicator_section_indicator_layout = global::RecyclerDemo.Resource.Styleable.AbsSectionIndicator_section_indicator_layout;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView = global::RecyclerDemo.Resource.Styleable.RecyclerView;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView_android_orientation = global::RecyclerDemo.Resource.Styleable.RecyclerView_android_orientation;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView_layoutManager = global::RecyclerDemo.Resource.Styleable.RecyclerView_layoutManager;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView_reverseLayout = global::RecyclerDemo.Resource.Styleable.RecyclerView_reverseLayout;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView_spanCount = global::RecyclerDemo.Resource.Styleable.RecyclerView_spanCount;
			global::RecyclerViewFastScroller.Resource.Styleable.RecyclerView_stackFromEnd = global::RecyclerDemo.Resource.Styleable.RecyclerView_stackFromEnd;
			global::RecyclerViewFastScroller.Resource.Styleable.SectionTitleIndicator = global::RecyclerDemo.Resource.Styleable.SectionTitleIndicator;
			global::RecyclerViewFastScroller.Resource.Styleable.SectionTitleIndicator_backgroundColor = global::RecyclerDemo.Resource.Styleable.SectionTitleIndicator_backgroundColor;
			global::RecyclerViewFastScroller.Resource.Styleable.SectionTitleIndicator_textColor = global::RecyclerDemo.Resource.Styleable.SectionTitleIndicator_textColor;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000b
			public const int backgroundColor = 2130771979;
			
			// aapt resource value: 0x7f010006
			public const int barBackground = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int barColor = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fast_scroller_layout = 2130771972;
			
			// aapt resource value: 0x7f010008
			public const int handleBackground = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int handleColor = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int section_indicator_layout = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int textColor = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080001
			public const int fastScrollBarColor = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int fastScrollHandleColor = 2131230720;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int list_item_height = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int margin_huge = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int margin_large = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int margin_medium = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int margin_small = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int margin_tiny = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fast_scroller_handle_round = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fast_scroller_handle_rounded = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int section_indicator_background_default_rounded = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int fast_scroller = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int fast_scroller_section_title_indicator = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int recycler_view = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int scroll_bar = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int scroll_handle = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int section_indicator_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int section_title_popup = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int section_indicator_with_title = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int vertical_recycler_fast_scroller_layout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int hello = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int library_name = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int text = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AbsRecyclerViewFastScroller = new int[]
			{
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 2
			public const int AbsRecyclerViewFastScroller_barBackground = 2;
			
			// aapt resource value: 1
			public const int AbsRecyclerViewFastScroller_barColor = 1;
			
			// aapt resource value: 0
			public const int AbsRecyclerViewFastScroller_fast_scroller_layout = 0;
			
			// aapt resource value: 4
			public const int AbsRecyclerViewFastScroller_handleBackground = 4;
			
			// aapt resource value: 3
			public const int AbsRecyclerViewFastScroller_handleColor = 3;
			
			public static int[] AbsSectionIndicator = new int[]
			{
					2130771977};
			
			// aapt resource value: 0
			public const int AbsSectionIndicator_section_indicator_layout = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SectionTitleIndicator = new int[]
			{
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int SectionTitleIndicator_backgroundColor = 1;
			
			// aapt resource value: 0
			public const int SectionTitleIndicator_textColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
